"""
GraphRAG Exporter Service for GitHub RAG.

Exports code chunks to text files for GraphRAG indexing.
Uses code-specific entity types (MODULE, CLASS, FUNCTION, PACKAGE, etc.).
"""

import logging
import subprocess
import sys
from datetime import datetime
from pathlib import Path
from typing import Optional

from config.settings import get_settings

logger = logging.getLogger(__name__)


class GraphRAGExporter:
    """
    Export code chunks to text files for GraphRAG entity/relationship extraction.

    The exported text preserves file structure and imports to help GraphRAG
    discover code-level relationships (imports, inheritance, API calls).
    """

    def __init__(self, graphrag_root: str):
        self.graphrag_root = Path(graphrag_root)
        self.input_dir = self.graphrag_root / "input"
        self.output_dir = self.graphrag_root / "output"
        self.input_dir.mkdir(parents=True, exist_ok=True)
        logger.info(f"GraphRAGExporter: {self.graphrag_root}")

    def export_chunks(
        self,
        chunks: list[dict],
        repo_owner: str,
        repo_name: str,
    ) -> Path:
        """
        Export chunks to a single text file for GraphRAG.

        Groups chunks by file path and preserves structural context.
        """
        output_lines: list[str] = []

        # Document header
        output_lines.append(f"# Repository: {repo_owner}/{repo_name}")
        output_lines.append(f"# Exported: {datetime.now().isoformat()}")
        output_lines.append(f"# Total chunks: {len(chunks)}")
        output_lines.append("")
        output_lines.append("---")
        output_lines.append("")

        # Group by file path for coherent reading
        by_file: dict[str, list[dict]] = {}
        for c in chunks:
            fp = c.get("file_path", "unknown")
            by_file.setdefault(fp, []).append(c)

        for file_path in sorted(by_file.keys()):
            file_chunks = by_file[file_path]
            lang = file_chunks[0].get("language", "")
            ctype = file_chunks[0].get("content_type", "code")

            output_lines.append(f"## File: {file_path}")
            if lang:
                output_lines.append(f"Language: {lang}")
            output_lines.append(f"Type: {ctype}")
            output_lines.append("")

            for chunk in file_chunks:
                section = chunk.get("section_header", "")
                parent = chunk.get("parent_class", "")
                chunk_type = chunk.get("chunk_type", "")

                if section and section != file_path:
                    label_parts = []
                    if chunk_type:
                        label_parts.append(chunk_type.capitalize())
                    if parent:
                        label_parts.append(f"in {parent}")
                    label_parts.append(section)
                    output_lines.append(f"### {' '.join(label_parts)}")
                    output_lines.append("")

                output_lines.append(chunk.get("content", ""))
                output_lines.append("")

            output_lines.append("---")
            output_lines.append("")

        # Write file
        safe_name = f"{repo_owner}__{repo_name}".replace("/", "_")[:100]
        output_path = self.input_dir / f"{safe_name}.txt"
        content = "\n".join(output_lines)
        output_path.write_text(content, encoding="utf-8")

        logger.info(f"Exported {len(chunks)} chunks ({len(by_file)} files) to {output_path}")
        logger.info(f"   File size: {len(content):,} characters")
        return output_path

    def create_config(
        self,
        azure_openai_endpoint: str,
        azure_openai_api_key: str,
        chat_model: str = "gpt-4.1",
        embedding_model: str = "text-embedding-3-large",
        entity_types: Optional[list[str]] = None,
    ) -> Path:
        """Create GraphRAG settings.yaml with code-specific entity types."""
        if entity_types is None:
            entity_types = [
                "MODULE",
                "CLASS",
                "FUNCTION",
                "PACKAGE",
                "API_ENDPOINT",
                "CONFIG",
                "SERVICE",
                "DATABASE",
                "TECHNOLOGY",
            ]

        settings_content = f"""# GraphRAG Configuration for GitHub Repository
# Auto-generated by Module 8 - GitHub RAG

models:
  default_chat_model:
    type: azure_openai_chat
    model: {chat_model}
    api_base: {azure_openai_endpoint}
    api_version: "2024-12-01-preview"
    deployment_name: {chat_model}
    api_key: ${{GRAPHRAG_API_KEY}}
    auth_type: api_key
    requests_per_minute: 60
    tokens_per_minute: 80000
    max_tokens: 4000
    temperature: 0

  default_embedding_model:
    type: azure_openai_embedding
    model: {embedding_model}
    api_base: {azure_openai_endpoint}
    api_version: "2024-12-01-preview"
    deployment_name: {embedding_model}
    api_key: ${{GRAPHRAG_API_KEY}}
    auth_type: api_key
    requests_per_minute: 120
    tokens_per_minute: 120000

input:
  type: file
  file_type: text
  base_dir: input

chunking:
  type: tokens
  size: 1200
  overlap: 100

extract_graph:
  entity_types:
{chr(10).join(f'    - {et}' for et in entity_types)}
  max_gleanings: 1

cluster_graph:
  max_cluster_size: 10

community_reports:
  max_length: 2000
  max_input_length: 8000

output:
  type: file
  base_dir: output

reporting:
  type: file
  base_dir: output/reports

snapshots:
  graphml: true
"""

        settings_path = self.graphrag_root / "settings.yaml"
        settings_path.write_text(settings_content, encoding="utf-8")

        # .env for GraphRAG
        env_content = f"GRAPHRAG_API_KEY={azure_openai_api_key}\nGRAPHRAG_API_BASE={azure_openai_endpoint}\n"
        (self.graphrag_root / ".env").write_text(env_content, encoding="utf-8")

        logger.info(f"Created GraphRAG config: {settings_path}")
        return settings_path

    def run_indexing(self, timeout: int = 600) -> dict:
        """Run GraphRAG indexing (synchronous, blocking)."""
        logger.info("🚀 Starting GraphRAG indexing...")
        lock_file = self.graphrag_root / ".indexing_in_progress"

        try:
            lock_file.write_text(f"Started: {datetime.now().isoformat()}")

            result = subprocess.run(
                [sys.executable, "-m", "graphrag", "index", "--root", str(self.graphrag_root)],
                capture_output=True,
                text=True,
                timeout=timeout,
                cwd=str(self.graphrag_root),
            )

            if result.returncode == 0:
                logger.info("✅ GraphRAG indexing complete!")
                output_files = list(self.output_dir.glob("*.parquet"))
                return {
                    "success": True,
                    "output_files": [f.name for f in output_files],
                }
            else:
                logger.error(f"❌ GraphRAG indexing failed: {result.stderr}")
                return {"success": False, "error": result.stderr}

        except subprocess.TimeoutExpired:
            return {"success": False, "error": f"Timed out after {timeout}s"}
        except Exception as e:
            return {"success": False, "error": str(e)}
        finally:
            if lock_file.exists():
                lock_file.unlink()

    def start_indexing_background(self) -> dict:
        """Start GraphRAG indexing in background (non-blocking)."""
        lock_file = self.graphrag_root / ".indexing_in_progress"
        if lock_file.exists():
            return {"success": False, "error": "Indexing already in progress", "is_indexing": True}

        try:
            lock_file.write_text(f"Started: {datetime.now().isoformat()}")
            log_file = self.graphrag_root / "logs" / "indexing-engine.log"
            log_file.parent.mkdir(parents=True, exist_ok=True)

            with open(log_file, "a") as lf:
                process = subprocess.Popen(
                    [sys.executable, "-m", "graphrag", "index", "--root", str(self.graphrag_root)],
                    stdout=lf,
                    stderr=subprocess.STDOUT,
                    cwd=str(self.graphrag_root),
                    start_new_session=True,
                )

            logger.info(f"✅ GraphRAG indexing started (PID: {process.pid})")
            return {"success": True, "pid": process.pid, "is_indexing": True}

        except Exception as e:
            if lock_file.exists():
                lock_file.unlink()
            return {"success": False, "error": str(e)}

    def get_status(self) -> dict:
        """Get GraphRAG index status."""
        lock_file = self.graphrag_root / ".indexing_in_progress"
        status = {
            "graphrag_root": str(self.graphrag_root),
            "input_documents": 0,
            "output_exists": self.output_dir.exists(),
            "has_parquet": False,
            "entities_count": 0,
            "relationships_count": 0,
            "communities_count": 0,
            "ready": False,
            "is_indexing": lock_file.exists(),
        }

        if self.input_dir.exists():
            status["input_documents"] = len(list(self.input_dir.glob("*.txt")))

        if self.output_dir.exists():
            parquet_files = list(self.output_dir.glob("*.parquet"))
            status["has_parquet"] = len(parquet_files) > 0
            status["parquet_files"] = [f.name for f in parquet_files]

            try:
                import pandas as pd

                ep = self.output_dir / "entities.parquet"
                if ep.exists():
                    status["entities_count"] = len(pd.read_parquet(ep))
                rp = self.output_dir / "relationships.parquet"
                if rp.exists():
                    status["relationships_count"] = len(pd.read_parquet(rp))
                cp = self.output_dir / "communities.parquet"
                if cp.exists():
                    status["communities_count"] = len(pd.read_parquet(cp))

                status["ready"] = status["entities_count"] > 0 and (self.output_dir / "community_reports.parquet").exists()
            except Exception:
                pass

        return status

    def clear(self) -> bool:
        """Clear all GraphRAG data (input + output)."""
        import shutil

        try:
            for p in (self.graphrag_root / ".indexing_in_progress",):
                if p.exists():
                    p.unlink()
            if self.input_dir.exists():
                shutil.rmtree(self.input_dir)
                self.input_dir.mkdir(parents=True, exist_ok=True)
            if self.output_dir.exists():
                shutil.rmtree(self.output_dir)
            logger.info("Cleared GraphRAG index")
            return True
        except Exception as e:
            logger.error(f"Failed to clear: {e}")
            return False
